apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app-poc
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      reconcileStrategy: Revision
      chart: app-poc
      version: "0.1.0-develop"
      sourceRef:
        kind: HelmRepository
        name: stable
        namespace: flux-system
      interval: 1m